use mysql;

DROP DATABASE IF EXISTS `mm`;
CREATE DATABASE `mm` CHARACTER SET utf8 COLLATE utf8_bin;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, TRIGGER ON `mm`.* TO 'mm'@'%' IDENTIFIED BY 'Dilip123';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, TRIGGER ON `mm`.* TO 'mm'@'localhost'  IDENTIFIED BY 'Dilip123';

FLUSH PRIVILEGES;

use `mm`;

CREATE TABLE `CANDIDATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_NAME` char(100) NOT NULL,
  `PHONE_NUMBER` char(11) ,
  `JOB` char(200) DEFAULT 'F',
   `AGE` int(11) DEFAULT 0,
  `GENDER` char(1) DEFAULT 'F',
  `SELF_REMARK` varchar(300) NOT NULL,
  `WEIGHT` float(5,2) DEFAULT 0,
  `HEIGHT` float(5,2) DEFAULT 0,
  `POLL` int(11) DEFAULT 0,
  `IMAGE_FILE_NAME` varchar(500),
   PRIMARY KEY (`ID`)
);


CREATE TABLE `WEIXIN_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_ID` bigint(20),
  `OPEN_ID` char(100) NOT NULL,
  `NICK_NAME` varchar(300),
   PRIMARY KEY (`ID`)
);

CREATE TABLE `VOTE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_ID` bigint(20),
  `USER_OPEN_ID` char(100) NOT NULL,
  `VOTE_TIME` DATETIME,
   PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_COUPON` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_ID` bigint(20),
  `COUPON_CODE` char(200) NOT NULL,
  `COUPON_PASSWORD` char(200) NOT NULL,
  `EXPIRE_TIME` DATETIME NOT NULL,
   PRIMARY KEY (`ID`)
);

