use `mm`;

ALTER TABLE `CANDIDATE` ADD COLUMN CREATED_DATE DATETIME;
ALTER TABLE `CANDIDATE` ADD COLUMN UPDATED_DATE DATETIME;
ALTER TABLE `CANDIDATE` MODIFY COLUMN `HEIGHT` INT(11);
ALTER TABLE `CANDIDATE` ADD COLUMN CANDIDATE_OPEN_ID char(32);
ALTER TABLE `VOTE` ADD COLUMN VOTE_IP_ADDR char(15);

ALTER TABLE `VOTE` DROP COLUMN `USER_OPEN_ID`;
ALTER TABLE `VOTE` ADD COLUMN `USER_OPEN_ID` char(32);


